version: 2
updates:
  ## Authorization
  - directory: "src/ResourceRegister"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  - directory: "src/Altinn.ResourceRegister.Integration"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
     

## Test
  - directory: "test/ResourceRegistryTest"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  
## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 10
