GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA resourceregistry TO platform_authorization;
GRANT ALL ON ALL SEQUENCES IN SCHEMA resourceregistry TO platform_authorization;

ALTER DEFAULT PRIVILEGES
FOR USER ${YUNIQL-USER}
IN SCHEMA resourceregistry
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON TABLES TO platform_authorization;

ALTER DEFAULT PRIVILEGES
FOR USER ${YUNIQL-USER}
IN SCHEMA resourceregistry
GRANT ALL ON SEQUENCES TO platform_authorization;
