GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA resourceregistry TO "${APP-USER}";
GRANT ALL ON ALL SEQUENCES IN SCHEMA resourceregistry TO "${APP-USER}";

ALTER DEFAULT PRIVILEGES
FOR USER "${YUNIQL-USER}"
IN SCHEMA resourceregistry
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON TABLES TO "${APP-USER}";

ALTER DEFAULT PRIVILEGES
FOR USER "${YUNIQL-USER}"
IN SCHEMA resourceregistry
GRANT ALL ON SEQUENCES TO "${APP-USER}";
