GRANT USAGE ON SCHEMA resourceregistry TO "${APP-USER}";
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA resourceregistry TO "${APP-USER}";
GRANT ALL ON ALL SEQUENCES IN SCHEMA resourceregistry TO "${APP-USER}";
