using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Altinn.ResourceRegistry.Core.Constants
{
    /// <summary>
    /// Constants related to resource registry
    /// </summary>
    public static class ResourceConstants
    {
        /// <summary>
        /// Prefix used for autogenerated service engine resources
        /// </summary>
        public const string SERVICE_ENGINE_RESOURCE_PREFIX = "se_";

        /// <summary>
        /// Prefix used for autogenerated app resources
        /// </summary>
        public const string APPLICATION_RESOURCE_PREFIX = "app_";

        /// <summary>
        /// Languace code for english  639-1
        /// </summary>
        public const string LANGUAGE_EN = "en";

        /// <summary>
        /// Language code for norwegian bokmål  639-1
        /// </summary>
        public const string LANGUAGE_NB = "nb";

        /// <summary>
        /// Language code for norwegian nynorsk  639-1
        /// </summary>
        public const string LANGUAGE_NN = "nn";
    }
}
